title: DPP Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://pretoms.github.io/dpp_docs_template

aux_links:
  Repository: https://github.com/pretoms/dpp_docs_template
