title: PP Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://pretoms.github.io/pp_docs_example

aux_links:
  Template Repository: https://github.com/pretoms/pp_docs_example
